### ISSUE TITLE
Version 3

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/lightnovel-crawler#336]
### Development branch

https://github.com/dipu-bd/lightnovel-crawler/tree/v3

### Tasklist
- [ ] Convert v2 sources
- [ ] Convert v2 binders
- [ ] Create console bot
- [ ] Create discord bot #369
- [ ] Create telegram bot #237 #236 #238 
- [ ] Create GUI bot #36 
- [x] Create an analyzer to build crawlers automatically #501 
- [ ] Add events to context, which will be listened by the pipelines, and used to perform their actions. convert all scraper and binders to pipelines

**Comment by dipu-bd** [comment]
- allow third party plugins like: text sanitizer, google translation, book binders etc
- pass (url, respose) to parser. parser should yield entities to store or more links to follow

**Comment by kuwoyuki** [comment]
Would be nice to move to some other [CLI library](https://github.com/vinta/awesome-python#command-line-interface-development) as `PyInquirer` depends on prompt_toolkit==1 which is dead (2 major releases behind and [not willing to upgrade](https://github.com/CITGuru/PyInquirer/issues/14)). Atm it breaks a lot of other packages if installed in user space.

**Comment by kuwoyuki** [comment]
Would be nice to move to some other [CLI library](https://github.com/vinta/awesome-python#command-line-interface-development) as `PyInquirer` depends on prompt_toolkit==1 which is dead (2 major releases behind and CITGuru/PyInquirer # 14.)
Atm it breaks a lot of other packages if installed in user space.

**Comment by dipu-bd** [comment]
@kuwoyuki Do you have any suggestion for CLI?

**Comment by kuwoyuki** [comment]
[questionary](https://github.com/tmbo/questionary) is a maintained fork of PyInquirer so that should be pretty easy to migrate to.

I personally really like [click](https://github.com/pallets/click/) though. It's pretty easy to build in and they have [shell completion] (https://click.palletsprojects.com/en/7.x/bashcomplete/).

**Comment by dipu-bd** [comment]
I like `questionary`. It has good documentation and lots of feature. Better than `PyInquirer`.

I don't know much about `click`. I used the default `argparse`. It gives a chance to group arguments, and define mutually exclusive arguments. I feel more comfortable using it. I will take a look how `click` works since you recommended it.

**Comment by MMDF** [comment]
I would recommend to add a sanitizer for html input from sites, cleaning up non-text html elements and not allowing script tags and generally things that arent supposed to be in an epub or web novel.

**Comment by dipu-bd** [comment]
moving from v2 sources is a lot of work. I don't have enough free time to spend here. 🐸
